// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6cvvZruTK_aY9s3Z8nkAWSLw8yvTx8N4',
    appId: '1:1029345451232:web:f760c4a5597104d1438485',
    messagingSenderId: '800017322402',
    projectId: 'gocarriage-b5173',
    authDomain: 'gocarriage-b5173.firebaseapp.com',
    storageBucket: 'gocarriage-b5173.firebasestorage.app',
    measurementId: 'G-LMFF33950N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCegewzfDwUhL32ektlfGrby8J2qVv6kho',
    appId: '1:1029345451232:android:0cfdc80c31c2b66d438485', // ✅ FIXED
    messagingSenderId: '1029345451232',
    projectId: 'gocarriage-b5173',
    storageBucket: 'gocarriage-b5173.firebasestorage.app',
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXeubNE_tTwh60ncXO84Hw9x6s7v5XrrA',
    appId: '1:1029345451232:ios:4430a3e26a3f0a87438485',
    messagingSenderId: '1029345451232',
    projectId: 'gocarriage-b5173',
    storageBucket: 'gocarriage-b5173.firebasestorage.app',
    iosBundleId: 'com.gocarriage',
  );

}